# Generated by Django 4.2.3 on 2023-07-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN', 'enabled'), ('DS', 'disabled')], default='EN', max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN', 'enabled'), ('DS', 'disabled')], default='EN', max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.entity')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.entity',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.entity')),
                ('Faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.faculty')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.entity',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.entity')),
                ('uc', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('ht', models.FloatField()),
                ('hp', models.FloatField()),
                ('hl', models.FloatField()),
                ('type', models.CharField(choices=[('MD', 'mandatory'), ('EL', 'elective')], max_length=2)),
                ('School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.school')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.entity',),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN', 'enabled'), ('DS', 'disabled')], default='EN', max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
                ('Section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.section')),
            ],
            options={
                'unique_together': {('Person', 'Section')},
            },
        ),
    ]
