# Generated by Django 4.2.3 on 2023-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cedula',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
